### ISSUE TITLE
Measurement function definition boundaries

### ISSUE THREAD

**Issue by wint3ria** [comet-toolkit/punpy#7]
It is possible that punpy generates input samples that are outside of the input definition boundaries of a measurement function. A classical example is when punpy generates values under zero for a physical quantity that can never be negative (for instance the concentration of a molecular species in a given medium).

It would be a great plus for punpy to provide a mechanism to avoid generating such values. This would mean passing to punpy a constraint list on the parameters and implementing these when generating samples.

I'm not sure how this can be implemented however, with a clear input format, and with a well defined mathematical behavior.

**Comment by pdevis** [comment]
This will need to be implemented in comet_maths. 
We have always intended to add further probability density functions in addition to gaussian.
A truncated gaussian and tophat PDF will be added in near future.

**Comment by pdevis** [comment]
This is now possible in v0.38 by setting "truncated_gaussian" as the pdf_shape in MCPropagation.generate_MC_sample.
a min and or max value can be specified in the pdf_params dictionary. If any element of a MC sample exceeds these values, a new MC draw will be generated (the full MC sample including all dimensions, since we need to maintain error correlations).

**Comment by wint3ria** [comment]
That's a some very good news, thank you

**Comment by pdevis** [comment]
see https://punpy.readthedocs.io/en/latest/content/punpy_standalone.html#different-probability-density-functions
